In [20]:
import numpy as np  

In [24]:
# 1. Broadcasting
# a) Add a 1D array `[1, 2, 3]` to each row of a 2D array `[[10, 20, 30], [40, 50, 60]]`.
a = np.array([1,2,3])
b = np.array([[10, 20, 30], [40, 50, 60]])
c = a + b
print(c)

# b) Multiply a 2D array `[[1, 2], [3, 4]]` by a 1D array `[10, 20]` column-wise
x = np.array([[1,2] ,
               [3,4]])
y = np.array([[10,20]]).reshape(2,1)
z = x * y
print(z)

[[11 22 33]
 [41 52 63]]
[[10 20]
 [60 80]]


In [26]:
# 2. Indexing and Slicing (High Dimensional Arrays)
arr = np.arange(1, 25).reshape(2, 3, 4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [27]:
# a) Extract the second slice along axis 0.
print(arr[1 , : ,:])

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [15]:
# b) Extract all rows and the last column for all slices.
print(arr[: , : , -1 ])

[[ 4  8 12]
 [16 20 24]]


In [29]:
# c) Reverse the order of slices along axis 0.
print(arr[::-1 , : , :])


[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [30]:
# d) Set all even elements in the array to -1.
arr[arr % 2 == 0] = -1
print(arr)

[[[ 1 -1  3 -1]
  [ 5 -1  7 -1]
  [ 9 -1 11 -1]]

 [[13 -1 15 -1]
  [17 -1 19 -1]
  [21 -1 23 -1]]]


In [32]:
# 3. np.repeat
# a) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where every odd element is repeated twice.

arr = np.array([1, 2, 3, 4, 5, 6])
newArr = np.repeat(arr[arr % 2 == 1], 2)
print(newArr)


# b) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where elements are repeated based on their value.

a = np.array([1, 2, 3, 4, 5, 6])
newArr2 = np.repeat(a , a)
print(newArr2)  


[1 1 3 3 5 5]
[1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6]


In [33]:
# 4. Normalizing
# a) Normalize a 1D array `arr = np.array([10, 20, 30])` to have values between 0 and 1.

arr = np.array([10, 20, 30])

normalizedArr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print(normalizedArr)

[0.  0.5 1. ]


In [34]:
# 5. Bonus Challenge
# a) Create a 3x3 matrix where each element at position (i, j) is i * j.

i = np.arange(3).reshape(3, 1)  
j = np.arange(3)              
matrix = i * j                  
print(matrix)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [35]:
# b) Given a 4x4 matrix, replace all elements on the main diagonal with 0 without using a loop.
arr = np.arange(16).reshape(4,4)
np.fill_diagonal(arr, 0)
print(arr)


[[ 0  1  2  3]
 [ 4  0  6  7]
 [ 8  9  0 11]
 [12 13 14  0]]
